### ISSUE TITLE
add ability to provide a custom regex for the classnames

### ISSUE THREAD

**Issue by omarkhatibgg** [ellreka/tailwindcss-highlight#109]
Hey, 

first of all thank you for this great plugin.

so I use `tailwind-variants` for theming my design system, `tailwind-variants` have an object-based class name, so in order to get IntelliSense we have a [custom regex for that](https://www.tailwind-variants.org/docs/getting-started#intellisense-setup-optional)

Could you provide a way to add a new custom regex in settings.json ?

by the way, I tried to rename the function with `tvclsx` and the highlight worked but it broke the object coloring as well

**Comment by KnifeFed** [comment]
I would love this feature to use with https://github.com/dcastil/tailwind-merge

**Comment by omarkhatibgg** [comment]
closing since no one even looked at it
