### ISSUE TITLE
Add vue support?

### ISSUE THREAD

**Issue by peteruithoven** [ellreka/tailwindcss-highlight#42]
I've tried mapping the `vue` language to multiple languages that tailwindcss-highlight knows, but none seem to work.

**Comment by ellreka** [comment]
@peteruithoven 
Sorry. I didn't notice your message.
I'll check.

**Comment by ellreka** [comment]
@peteruithoven 

Have you tried adding `vue` to `tailwindcss-highlight.languages` ?

https://github.com/ellreka/tailwindcss-highlight#languages

**Comment by peteruithoven** [comment]
Thanks for the tip! I'm sorry I didn't try that before. 
It does seem to work! 
(I'm noticing some `class`'es being ignored, but I'll open a separate issue for that.)
