### ISSUE TITLE
Add option to change styling

### ISSUE THREAD

**Issue by joostclevis** [ellreka/tailwindcss-highlight#43]
If you have a lot of classes the html looks very busy and cluttered. It would be nice if there was an option to change the layout. Instead of a background color maybe a border-bottom color or something like that.

**Comment by ellreka** [comment]
@joostclevis 
Sorry. I didn't notice your message.
I'll check.

**Comment by ellreka** [comment]
@joostclevis 

You can set a custom style in the extension settings.
Also, If there are classes you do not need, set enabled to false.

https://github.com/ellreka/tailwindcss-highlight#configs

Example:
```settings.json
  "tailwindcss-highlight.configs": {
    "padding": {
      "enable": true,
      "regex": "(?<=[:`'\"\\s])(|-)p(|t|b|r|l|x|y)-[^`'\"\\s]+",
      "options": {
        "backgroundColor": "",
        "borderWidth": "0 0 3px 0",
        "borderStyle": "solid",
        "borderColor": "rgba(187, 196, 136, 1)",
        "color": "currentColor"
      }
    },
  }
```
![スクリーンショット 2022-04-16 3 08 55](https://user-images.githubusercontent.com/28590054/163605732-fab4a369-4000-4b2c-8f60-dff64ea9802b.png)
