### ISSUE TITLE
Some classes in Vue templates are ignored?

### ISSUE THREAD

**Issue by peteruithoven** [ellreka/tailwindcss-highlight#51]
I notice that some classes in Vue templates seem to be ignored? 

I realize not every class is highlighted in general but `flex` is highlighted sometimes. If I move some of the items like `w-8` from to a different `class` attribute they are then highlighted. 
I thought it might be incompatible with those color indicating rectangles, but those also appear in `class`'es that are highlighted. 

![Screenshot from 2022-04-14 15-15-07@2x](https://user-images.githubusercontent.com/523210/163399796-80e51dea-63a1-49d8-b1a7-022c6a8c005a.png)

``` vue
<template>
  <div
    v-show="collapsed"
    class="cursor-pointer border border-primary-500 hover:bg-blueGray-700 rounded px-4 py-2 flex items-center mt-6"
    @click="collapsed = !collapsed"
  >
    <div class="mr-1">
      <h5 class="text-sm mb-0.5 text-white">Explore the data</h5>
      <p class="text-xs leading-tight text-primary-300">
        Click here to reveal relevant charts & statistics.
      </p>
    </div>
    <div class="flex items-center">
      <div
        class="scale-[-1] bg-primary-600 rounded-full w-8 h-8 flex items-center justify-center"
      >
        <Chevron class="w-6 h-6 text-white" />
      </div>
    </div>
  </div>
</template>
```

![Screenshot from 2022-04-14 15-21-18@2x](https://user-images.githubusercontent.com/523210/163399836-4cf51e42-4f90-4d59-a979-b0b74d41af89.png)
``` vue
<template>
  <div
    class="rounded shadow text-center h-6 text-xs absolute left-1/2 py-1 px-2 pointer-events-none bottom-[calc(100%+0.6rem)] bg-white select-none -translate-x-1/2"
  >
    <slot />
    <div class="absolute top-full -translate-x-1/2 left-1/2">
      <TooltipArrowWide class="w-[9px] h-[7px] text-white" />
    </div>
  </div>
</template>
```

Let me know if you need me to create an example you can run yourself or you need more info in general.

**Comment by peteruithoven** [comment]
Who that's quick. My first example works great now. 

In the second one the `bottom-[calc(100%+0.6rem)]` still seem to cause issues. Looks like the `%` and `+` are the tricky bits? I don't fully get the regular expression yet, but maybe you need to add the `%` and `+` as possible characters?

**Comment by ellreka** [comment]
@peteruithoven 

Thanks!

Fixed this bug in `v1.2.4`.

Please update.

**Comment by peteruithoven** [comment]
Ah, maybe I was testing with another release you just did. 
But for some reason it no longer works for me. I'm getting no highlighting anymore. 

Through `code --list-extensions --show-versions` I know I now have `ellreka.tailwindcss-highlight@1.2.4`. 

I've restarted Visual Studio Code multiple times. 

I've added `vue-html` to the languages just to be sure. 

My language settings:
```
"tailwindcss-highlight.languages": [
  "html",
  "javascript",
  "javascriptreact",
  "typescript",
  "typescriptreact",
  "vue",
  "php",
  "svelte",
  "vue-html"
]
```
Extension page:
![Screenshot from 2022-04-14 18-14-06@2x](https://user-images.githubusercontent.com/523210/163430933-c6cdc127-2efb-45dd-92e0-a241b486c531.png)

Even a simple icon vue file doesn't work:
``` vue
<template>
  <svg
    class="flex-none"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
    fill="currentColor"
  >
    <path
      d="M11 7h2v2h-2zm0 4h2v6h-2zm1-9C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8z"
    />
  </svg>
</template>
```

I really don't want to drag you into debugging my situation. Maybe just wait whether other people report the problem?

**Comment by ellreka** [comment]
@peteruithoven

Sorry...

The extension is broken because I updated tsconfig.json.

Please update again as I've confirmed it's fixed in v1.2.5.

**Comment by peteruithoven** [comment]
Ahh totally works! :partying_face:

**Comment by ellreka** [comment]
Thank you!
